apiVersion: apps/v1
kind: Deployment
metadata:
  name: result-deployment
  namespace: vote
spec:
  selector:
    matchLabels:
      app: demo-voting-app
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-voting-app
      spec:
        containers:
        - name: result
          image: kodekloud/examplevotingapp_result:v1
          ports: 
              - containerPort: 80