apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  namespace: vote
  labels:
    name: vote-deployment
    app: vote-deployment 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote-deployment
  template:
    metadata:
      labels:
        app: vote-deployment
    spec:
      containers:
      - name: vote
        image: kodekloud/examplevotingapp_vote:before
        resources: {}
        ports:
          - containerPort: 80