apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-deployment
  labels:
      app: demo-voting-app
spec:
  selector:
    matchLabels:
      app: demo-voting-app
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-voting-app
    spec:
      containers:
        - name: vote
          image: kodekloud/examplevotingapp_vote:before
          ports:
            - containerPort: 80
      nodeSelector:
          role: worker
