apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker-deployment
spec:
  selector:
    matchLabels:
      app: demo-voting-app
  replicas: 1
  template:
    metadata:
      labels:
        app: demo-voting-app
    spec:
      containers:
        - name: worker
          image: kodekloud/examplevotingapp_worker:v1
      nodeSelector:
          role: worker